config/routes.rb
Rails.application.routes.draw do
  root "hello#index"

  resources :sources
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :source
end

app/models/source.rb
class Source < ApplicationRecord
    has_one_attached :csv

    has_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_codespaces_helper.rb
module HelloCodespacesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/views/hello/index.html.erb
<div class="App">
  <header class="App-header">
    <p>
    <%= link_to 'Upload a new report', new_source_path %>
    </p>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodespacesTryRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sources/new.html.erb
<h1>Upload a new expense report</h1>

<%= form_with model: @source do |form| %>

<div>
    <%= form.label :source_type %>
    <%= form.collection_select(
        @source, 
        :source_type, 
        CsvProcessorDispatcher.processors, 
        (processor)-> { processor.name },
        (processor)-> { processor.processor_name }
        ) 
    %>
</div>

<div>
    <%= form.label :label %>
    <%= form.text_field :label %>
</div>

<div>
    <%= form.label :csv %>
    <%= form.file_field :csv %>
</div>

<div>
  <%= form.submit %>
</div>

<% end %>